# Generated by Django 5.0.1 on 2024-02-08 15:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Статья'),
        ),
    ]
